### ISSUE TITLE
can we access Connection.is_server ?

### ISSUE THREAD

**Issue by keepsimple1** [cloudflare/quiche#1078]
https://github.com/cloudflare/quiche/blob/3ea9bf4f9ae9bea61213f26a0f46d837ac95b207/src/lib.rs#L1099-L1100

it seems like there is no public method to access `Connection.is_server`.  Is there a plan to add one? Or is there some concern about adding such method? 

Thanks.

**Comment by LPardue** [comment]
The application would have the knowledge about if its a server or a client, that determines how it behaves on multiple layers. What benefit would there be to expose that information from quiche?

**Comment by keepsimple1** [comment]
It's true that the application can maintain this state by itself.  However that will bring up a question: which one is the source of truth. IMO, It will be simpler & cleaner to just query the QUIC connection.

**Comment by LPardue** [comment]
Since QUIC is a client / server transport, so are the applications on the top. That determines how applications use the transport, and that knowledge is needed in order to initialise any connection. It would seem strange for an application to initialize a connection object in a role and then not be aware of what the source of truth is. 

Do you have a concrete use case why this information needs to be exposed? Bearing in mind things like socket I/O that needs to be initialized and maintained by applications and won't be a part if a QUIC connection?

**Comment by keepsimple1** [comment]
In my use case, an endpoint could serve h3 requests, or initiate h3 requests using the same connection. One option is to use stream_id (even or odd) and connection is_server flag to distinguish different types requests.  A bit like `stream::is_local()` in quiche. Yes, I understand all socket I/O are maintained by applications. not in quiche.

**Comment by LPardue** [comment]
That's not valid HTTP/3

**Comment by keepsimple1** [comment]
Okay. It's allowed in QUIC, but I guess not in HTTP/3. Will check more for options.

**Comment by LPardue** [comment]
QUIC has no opinion on how streams actually get _used_, thats a function of the application protocol mapping. So there's going to need to be some layer above the quiche connection object that implements such an application mapping; it may or may not care about the client or server role. But if it cares it's trivial or it to track itself because it is most likely an invariant property of the instance that was created. 

Concerns over multiple sources of truth are stronger where the values are dynamic and there is a real risk of the system becoming desynchronized, but in this case a piece of software that is a client, is very likely to always be a client no matter where that information is distributed through software components.
