### ISSUE TITLE
API: custom pointer per (h3) stream?

### ISSUE THREAD

**Issue by bagder** [cloudflare/quiche#112]
When doing multiplexed h3 streams over the same QUIC connection.

It would be helpful for my code (and presumably others') if we could assign an opaque pointer to the h3 stream when such is created, and then quiche could deliver that pointer when it returns events for that stream. It will save me from having to implement the same stream-to-pointer hash lookup.

**Comment by ghedo** [comment]
Yeah, makes sense. I've been thinking of doing something like this for quiche's own HTTP/3 implementation so we wouldn't have to maintain two separate stream maps (one for transport and one for h3).

One idea would be to have transport-level stream user data (that can be used by quiche h3) and h3-level stream user data that can be used by curl (or whatever other application).

Will need to figure out an API that prevents the application from accidentally using the wrong type of user data though or things could get messy pretty easily. Will also need to design it so that it makes Rust's safety police happy :)
