### ISSUE TITLE
How do I verify the server certificate?

### ISSUE THREAD

**Issue by bagder** [cloudflare/quiche#1120]
Hi team.

Using the C API, I need my client to verify the server certificate proper (== that it is signed by a CA and that the name field in the cert match the one I connect to) but I can't figure out how to do this. Any clues?

(related: https://github.com/curl/curl/issues/8173)

**Comment by LPardue** [comment]
Looking at the curl ticket, it seems you want to implement a similar pattern as https://github.com/cloudflare/quiche/issues/326. Is that about right?

I think the function is just not exposed to the C API due to oversight.

**Comment by LPardue** [comment]
@bagder does https://github.com/cloudflare/quiche/pull/1122 help you?

**Comment by bagder** [comment]
Yes, that looks exactly what I need!

**Comment by ghedo** [comment]
PR is merged now, though FWIW, curl can also create the `SSL` pointer directly and pass it to quiche when creating a connection via https://github.com/cloudflare/quiche/blob/master/quiche/include/quiche.h#L262-L266

Then it can call BoringSSL functions on the pointer directly (and do whatever it does now for normal TLS), but that would probably require some larger refactoring of the QUIC code in curl.

**Comment by bagder** [comment]
> FWIW, curl can also create the SSL pointer directly and pass it to quiche when creating a connection

I think I'm going to need some more help with that than just a prototype in a header file.

It turns out that with OpenSSL (and thus boring) the peer certificate check against the CA cert bundle is done by the library itself (if told to ahead of time with `SSL_CTX_set_verify()`) and for me to do it after the fact when I get just the peer cert seems maybe not impossible but require something I don't even know where to start to get done!

Ie: with this new API I can extract the cert and verify that the name in there is fine. But verifying that it is signed by a trusted CA as well is another matter...

**Comment by ghedo** [comment]
The idea is to do something similar to what the ngtcp2 backend does  in `quic_ssl_ctx()` and `quic_init_ssl()`, and then, instead of calling `quiche_connect()` when creating the QUIC connection, you can call `quiche_conn_new_with_tls()` instead and pass the `SSL` pointer that was previously created in `quic_init_ssl()`.

Given that curl creates the `SSL_CTX` and `SSL` pointers, it can then configure them however it wants (e.g. calling `SSL_CTX_set_verify()` and whatnot). I made https://github.com/curl/curl/pull/8275 to show this (haven't tested it much though).
