### ISSUE TITLE
Immutable config when creating new connection?

### ISSUE THREAD

**Issue by nqv** [cloudflare/quiche#114]
Looks like `Config` in `Connection::with_tls` can be immutable https://github.com/nqv/quiche/commit/5bab541f4c2c6c16845993e7a09b13d360561eee.
I'm wondering if it's possible to make it immutable in `Connection::new` as well (e.g. clone tls::Context or something?).
Asked because while working on the C api, I'm not sure if I can free `quiche_config` after connection is established

**Comment by ghedo** [comment]
As far as quiche is concerned, it is safe to free the config after the connection is created and config doesn't need to be immutable in `Connection::new` for this to work (and indeed it needs to be mutable).

**Comment by cretz** [comment]
> and indeed it needs to be mutable

Sorry to comment on closed issue, just stumbled across this as I now have to decide whether to put some kind of mutex around a shared config or recreate the configuration for every `accept` call. I see the example server code shares the same configuration over and over because it assumes synchronous operation.

Suggestions? Worth making config copyable or is config reuse in asynchronous situations not going to be supported?
