### ISSUE TITLE
Connection implements Unpin but needs to be pinned

### ISSUE THREAD

**Issue by ColonelThirtyTwo** [cloudflare/quiche#1210]
`quiche::connect` returns a `Pin<Box<Connection>>`. According to https://github.com/cloudflare/quiche/pull/249#issue-519321868 this is because `Connection` contains pointers to its internal contents.

However `Connection` automatically implements `Unpin`, so you can move it out of the pin via `Pin::into_inner`, causing unsafety in safe code.

`Connection` should have a `PhantomPinned` member, and methods on it taking `&mut self` should be changed into taking `self: Pin<&mut Self>`.

**Comment by ghedo** [comment]
Thanks for reporting this!

In retrospect, I think wrapping `Connection` in `Pin<Box<...>>` was probably excessive, as we don't need the `Connection` pointer to be stable for the whole lifetime of the structure.

I made https://github.com/cloudflare/quiche/pull/1227 to show this which I think also fixes this issue due to removing the need for `Pin` in the first place.
