### ISSUE TITLE
Socks5 support

### ISSUE THREAD

**Issue by 0xFar5eer** [cloudflare/quiche#1301]
Is it possible to add Socks5 proxy support ?

**Comment by LPardue** [comment]
The quiche library is agnostic to sockets, so really its up to applications to support SOCKS if they want. 

The apps are intended mainly as demos or simple test tools. Adding SOCKS isupport s feasible but probably low on the priority list. A simpler workaround is to use something like socksify that can inject that behaviour rather than require explicit changes - https://linux.die.net/man/1/socksify. Does that solve your use case?

**Comment by 0xFar5eer** [comment]
Is it possible to specify my own ssl library then and custom transport protocol?
For example I would use boring-ssl and somehow my own socks library.
I need to add SOCKS support from rust code itself, socksify wouldn't work.

Is there any libraries such as reqwest supporting quiche, allowing to do GET/POST requests?

**Comment by LPardue** [comment]
Swapping tls is feasible but might be complicated depending on how the alternative works.

Quiche parses or create QUIC packets, that apps can read or write over any carriage. You can straightforwardly substitute UDP socket read/write for Rust SOCKS library equivalent and it'll work, I've seen that. 

We don't offer integration with reqwest or hyper here. But aware of various work that made that happening by gluing it all together. The low-level of quiche makes it very flexible to different purposes, but requires a little more glue to fit the desired environment.

**Comment by 0xFar5eer** [comment]
Thank you!
