### ISSUE TITLE
Question: is it possible to shutdown `Shutdown::Read` on a local unidirectional stream?

### ISSUE THREAD

**Issue by Banyc** [cloudflare/quiche#1317]
Hi I'm new to QUIC, still reading RFC 9000.

```rust
pub fn stream_shutdown(
    &mut self, stream_id: u64, direction: Shutdown, err: u64,
) -> Result<()> {
```

If the stream is a locally initiated unidirectional stream, is it possible to shutdown its receiving stream by sending `STOP_SENDING`?

**Comment by LPardue** [comment]
Good question!

Currently stream_shutdown with Shutdown::Read will cause a STOP_SENDING to be emitted. However, a local uni stream doesn't have a read side, so this is confusing. Per https://www.rfc-editor.org/rfc/rfc9000.html#name-stop_sending-frames

>  An endpoint that receives a STOP_SENDING frame for a receive-only stream MUST terminate the connection with error STREAM_STATE_ERROR

quiche enforces this behaviour on the receiver of STOP_SENDING, so that's good. However, we should probably improve stream_shutdown to prevent it sending the frame in the first place.

**Comment by LPardue** [comment]
Please see #1318, which should help make quiche clearer to use
