### ISSUE TITLE
Why have `at` field in `SendInfo` struct?

### ISSUE THREAD

**Issue by tbu-** [cloudflare/quiche#1377]
According to [the `SendInfo` documentation](https://docs.rs/quiche/0.16.0/quiche/struct.SendInfo.html), it is used to [pace](https://docs.rs/quiche/0.16.0/quiche/index.html#pacing) outgoing packets. The quiche API already allows quiche to pace packets by only handing them to the user after a timeout. Why was this additional method added?

**Comment by FranzBusch** [comment]
Ran into this as well. Opened a PR with a potential fix: https://github.com/cloudflare/quiche/pull/1403

**Comment by tbu-** [comment]
I think you mean #1376, this issue is about removing `at` from `SendInfo` completely.

**Comment by tbu-** [comment]
> This isn't true. We manage several QUIC protocol timers internally, and their expiration might require that the endpoint emits a new packet. But those timers do no fire for each and every packet.

I'm not sure I understand your point. As far as I can tell, the current quiche API has two ways of communicating that a packet should be sent at a certain point in time.

Method 1:

Return a packet with `SendInfo::at` set to a point in the future.

Method 2:

Wait until the point in the future before returning a packet.



This seems redundant. Why does quiche need two methods for doing that?



> The `at` field allows an application to extract a flight of packets from quiche and pace them.

Why is that better than quiche pacing the packets?

**Comment by LPardue** [comment]
Calling send() returns a packet. For optimal performance, you'll want to send a well-paced flight of packets. The pacing rate is a property of the congestion controller but the size of flight is a property of the implementation and its network stack. 

Since quiche's design externalizes event and timing responsibilities, your method 2 doesn't work if an application wants to get flight of packets, unless quiche returned a duration that informed the application how long to wait until calling send() again (or a timepoint to call it). That requires an application to have to run an additional timer. Instead, by using a send at time, the application can, for example, offload pacing to the network stack

**Comment by tbu-** [comment]
> unless quiche returned a duration that informed the application how long to wait until calling send() again […] That requires an application to have to run an additional timer.

I think this is done for some packets using the [`timeout`](https://docs.rs/quiche/0.18.0/quiche/struct.Connection.html#method.timeout) method already.

> Instead, by using a send at time, the application can, for example, offload pacing to the network stack

I see. If the intention is offloading it to the network stack, I guess it makes sense.

Thanks for bearing with me and thanks for the explanation.
