### ISSUE TITLE
nginx patch breaks content-type header

### ISSUE THREAD

**Issue by xfalcox** [cloudflare/quiche#237]
I added support for HTTP3 in the Discourse project here: https://github.com/discourse/discourse_docker/compare/http3

After deploying it to production and testing using `google-chrome-unstable --enable-quic --quic-version=h3-23 --origin-to-force-quic-on=example.com`, the requests for my HTML routes are missing the `content-type` header. Is this a know bug?

Testing with curl for HTTP2 has content-type:

```
curl -I https://forum.muito.ninja/latest
HTTP/2 200
...
content-type: text/html; charset=utf-8
....
```

Testing with quiche client doesn't have the content-type:

```
RUST_LOG=info target/debug/examples/http3-client https://forum.muito.ninja/latest

**Comment by junhochoi** [comment]
$ curl --http3 -vso/dev/null 'https://forum.muito.ninja/images/wizard/bubbles.png'
*   Trying 159.203.98.162:443...
* Sent QUIC client Initial, ALPN: h3-23
* h3 [:method: GET]
* h3 [:path: /images/wizard/bubbles.png]
* h3 [:scheme: https]
* h3 [:authority: forum.muito.ninja]
* h3 [user-agent: curl/7.67.0-DEV]
* h3 [accept: */*]
* Using HTTP/3 Stream ID: 0 (easy handle 0x7fde6700c000)
> GET /images/wizard/bubbles.png HTTP/3
> Host: forum.muito.ninja
> user-agent: curl/7.67.0-DEV
> accept: */*
>
< HTTP/3 200
< server: nginx
< date: Fri, 25 Oct 2019 22:48:01 GMT
< content-type: image/png
< content-length: 29108
< last-modified: Fri, 25 Oct 2019 15:55:32 GMT
< accept-ranges: bytes
<
{ [1032 bytes data]
* Connection #0 to host forum.muito.ninja left intact

**Comment by xmapst** [comment]
@junhochoi How did you get curl to support http3?

**Comment by junhochoi** [comment]
@xmapst https://github.com/curl/curl/blob/master/docs/HTTP3.md

**Comment by xmapst** [comment]
Thank you

**Comment by xfalcox** [comment]
Hey @junhochoi I just compiled `curl` with quiche HTTP3 enabled and if I do two requests:


```bash
curl --http3 -vso/dev/null 'https://forum.muito.ninja/latest'

curl  -vso/dev/null 'https://forum.muito.ninja/latest'
```

The version with `--http3` flag doesn't receive a `Content-Type` header back, while the one without it receives it.

**Comment by junhochoi** [comment]
@xfalcox so here is a summary:

https://forum.muito.ninja/latest with http3 - WITHOUT content-type header
https://forum.muito.ninja/latest with http2 - WITH content-type header

But content-type header is always with static objects:

https://forum.muito.ninja/images/wizard/bubbles.png with http3 - WITH content-type
https://forum.muito.ninja/images/wizard/bubbles.png with http2 - WITH content-type

Since for static objects nginx + quiche doesn't remove content-type header, so I wonder if this is something happening with Ruby on Rails engine.

Also AFAIK our patch doesn't modify/remove content-type header.

**Comment by xfalcox** [comment]
>  I wonder if this is something happening with Ruby on Rails engine.

How could that be since the Rails app is behind the nginx reverse proxy, and only speaks HTTP1.1 with the proxy, which then speaks HTTP1 2 or 3 with the external world.

**Comment by ghedo** [comment]
@xfalcox could you please share debug logs from NGINX when doing the HTTP/2 and HTTP/3 requests? You need to rebuild NGINX with the `--with-debug` configure option, and enable debug logs on the server (i.e. `error_logs ... debug` in the top level of the configuration).

**Comment by xfalcox** [comment]
Just an update, I can' reproduce this in Firefox. Only in Google Chrome.

**Comment by hguandl** [comment]
I can reproduce this by adding `accept-encoding` header. cURL accepts no encoding method by default since the compressed binary cannot be displayed friendly in terminal. However, web browsers usually use gzip or brotli to reduce speed up the transmission.

For the plain response body, the `content-type` headers is sent normally:
```
$ curl 'https://example.com/foo.js' --http3 -I
HTTP/3 200
server: nginx
date: Thu, 13 Feb 2020 17:23:25 GMT
content-type: application/javascript; charset=utf-8
vary: Accept-Encoding
last-modified: Mon, 10 Feb 2020 05:26:12 GMT
accept-ranges: bytes
x-content-type-options: nosniff
```
If cURL supports encodings such as gzip or brotli, the `content-type` is missing:
```
$ curl 'https://example.com/foo.js' --http3 -I -H 'accept-encoding: gzip, br'
HTTP/3 200
server: nginx
date: Thu, 13 Feb 2020 17:23:06 GMT
vary: Accept-Encoding
last-modified: Mon, 10 Feb 2020 05:26:12 GMT
x-content-type-options: nosniff
content-encoding: br
```
These encoding methods are widely used in text files including css, js and html. Without content-type the browser cannot parse the webpage correctly.

**Comment by xfalcox** [comment]
Thanks for the reproduction @hguandl !

Indeed my first encounter with this bug was due to CSS not loading.
