### ISSUE TITLE
Make project a workspace?

### ISSUE THREAD

**Issue by jaysonsantos** [cloudflare/quiche#24]
Hey there, while checking the code I saw that there are 2 things that could be used as separate crates, they are the h3 encode/decoder and octets.
What do you think of making this project a workspace and make it build smaller crates that could be published separately?
Let me know if you would like to see that implemented and I can try and make it as a first contribution to the project.

**Comment by jaysonsantos** [comment]
If you think this is a good idea, both modules depend on Error and Result from the main crate, would be good to also move these to a crate like quiche-results/errors or something like that?

**Comment by ghedo** [comment]
I'm not sure I understand why we would want this. The HTTP/3 API will require the base quiche one, so it doesn't really gain us much and it seems like it would make the release process somewhat more complicated. Having everything in the same crate also makes it easier to interface with C/C++ since you'd only have to care about a single static library instead of multiple ones.

As for octets module, I've been thinking about splitting it off for a while, but right now I don't have much use for it outside of quiche and the octets API has a bunch of QUIC-specific things and is not really stable at this point, so I'd rather keep it private for now, but this might change in the future.

However we will split the error code spaces when we will actually have a more complete HTTP/3 API, so there's that I guess.

**Comment by jaysonsantos** [comment]
Oh, right. Thanks for the answer.
