### ISSUE TITLE
allowed frames checking issues

### ISSUE THREAD

**Issue by agrover** [cloudflare/quiche#260]
Hi, hope this is useful. @martinthomson also says there will be a chart in a future draft to make this clearer, too.

* PING is allowed in all epochs (new in draft 24)
* Only ConnectionClose with type TransportError are forbidden in ZeroRTT
* NEW_TOKEN not allowed in ZeroRTT

**Comment by ghedo** [comment]
The PING case is fixed in https://github.com/cloudflare/quiche/pull/261 with the addition of draft-24 support.

For CONNECTION_CLOSE, we actually have a different frame type for the application close (`ApplicationClose`), so I think this is already correct?

For NEW_TOKEN, the draft only says `Note that it is not possible to send the following frames in 0-RTT for various reasons...` so it's not quite clear if we should really block it or not, but I guess we could. This also applied to PATH_RESPONSE, and RETIRE_CONNECTION_ID as well.

**Comment by ghedo** [comment]
This was actually fixed as part of https://github.com/cloudflare/quiche/pull/126.
