### ISSUE TITLE
server cannot create stream

### ISSUE THREAD

**Issue by jasonYellow** [cloudflare/quiche#301]
We modified the demo. When the connection is established, the server receives the data with stream ID 4 from the client,and then sends stream data with ID 5，but quiche_conn_stream_send return 0.
Thx.

**Comment by ghedo** [comment]
Without more information, like the actual code you wrote, log output from both client and server, etc..., it won't be possible for us to provide any help.

**Comment by jasonYellow** [comment]
Thank you very much for your reply!
I uploaded my project to GitHub. https://github.com/jasonYellow/Aquarius. 
It's almost the same as Example, I only modified the code in line 352 of the service.c and used ID 5 to send stream data.But it doesn't seem to work.

**Comment by LPardue** [comment]
hi @jasonYellow thanks for the repro.

In this case quiche is working as intended but it is implementing a part of the specification that is a bit counterintuitive. The reason you see `quiche_conn_stream_send` return 0 when sending on a server-initiated bidirectional stream is because the client does not provide any stream flow control credit. From https://tools.ietf.org/html/draft-ietf-quic-transport-24#section-18.2

> initial_max_stream_data_bidi_remote (0x0006):  This parameter is an
      integer value specifying the initial flow control limit for peer-
      initiated bidirectional streams.  This limit applies to newly
      created bidirectional streams opened by the endpoint that receives
      the transport parameter.  In client transport parameters, this
      applies to streams with an identifier with the least significant
      two bits set to 0x1; in server transport parameters, this applies
      to streams with the least significant two bits set to 0x0.

To fix this, in your client you need to add the following:

```
quiche_config_set_initial_max_stream_data_bidi_remote(config, 1000000);
```

**Comment by jasonYellow** [comment]
thank you!@LPardue.it worked.
