### ISSUE TITLE
Hit with TlsFail in handshake

### ISSUE THREAD

**Issue by tomoechan** [cloudflare/quiche#363]
HI, I'm trying to create a proxy for tcp traffic with quiche as its transport, so far it is yet functional due to hanged handshake, last recv() call returned TlsFail and from there both client and server return true when is_close() is called.

I tried the certificate and key in example and it gave similar trace log and error. I explicitly set no verify in client, use all 0s as client's scid, and use the dcid in client's first packet arriving at server as server's scid, and no odcid in server, no stream related operation is made as is_established() never returns true.

I use tokio to handle asynchronous socket writing and reading, other parts of this program should be unlikely to cause this problem as the program didn't proceed far into those parts

trace's of client and server are attached, those lines without timestamp are output of my program, basically they describe the same read or write as those trace's proceeding them. Please have a look and any suggestion is welcome, I'm really hyped by QUIC's potential as a good transport for proxy. Thank you.

[log_client.txt](https://github.com/cloudflare/quiche/files/4209906/log_client.txt)
[log_server.txt](https://github.com/cloudflare/quiche/files/4209908/log_server.txt)

**Comment by LPardue** [comment]
Thanks for attaching logs.

Out of interest, what ALPN ID are you using in your use case?

**Comment by ghedo** [comment]
As @LPardue suggested, it looks like the connection fails because there is no ALPN negotiated between the client and server.

You need to configure the client and the server such that they can negotiate the appropriate ALPN, see https://docs.quic.tech/quiche/struct.Config.html#method.set_application_protos

**Comment by VMatrix1900** [comment]
> HI, I'm trying to create a proxy for tcp traffic with quiche as its transport, so far it is yet functional due to hanged handshake, last recv() call returned TlsFail and from there both client and server return true when is_close() is called.
> 
> I tried the certificate and key in example and it gave similar trace log and error. I explicitly set no verify in client, use all 0s as client's scid, and use the dcid in client's first packet arriving at server as server's scid, and no odcid in server, no stream related operation is made as is_established() never returns true.
> 
> I use tokio to handle asynchronous socket writing and reading, other parts of this program should be unlikely to cause this problem as the program didn't proceed far into those parts
> 
> trace's of client and server are attached, those lines without timestamp are output of my program, basically they describe the same read or write as those trace's proceeding them. Please have a look and any suggestion is welcome, I'm really hyped by QUIC's potential as a good transport for proxy. Thank you.
> 
> [log_client.txt](https://github.com/cloudflare/quiche/files/4209906/log_client.txt)
> [log_server.txt](https://github.com/cloudflare/quiche/files/4209908/log_server.txt)

Can you share your tokio program? I want to use tokio instead of mio too.

**Comment by dbenoy** [comment]
I encountered this same problem. I'm going to add this here to help others who are searching for the solution to this in the future:
[2022-07-15T22:57:32Z TRACE quiche::tls] error:10000133:SSL routines:OPENSSL_internal:NO_APPLICATION_PROTOCOL

I'm a QUIC newbie (And TLS and rust, heh) so even though this trace log output technically was telling me what the problem was, I didn't understand what NO_APPLICATION_PROTOCOL meant. I didn't even know whether it was a bug because I could see that it was not generating any handshake packets at all, but also telling me that TLS failed. It also even mentioned 'OPENSSL_internal' making me wonder even further if there was something going on that was buried deep in quiche.

But the answer is that calling set_application_protos is required.

Perhaps the Getting Started documentation should be updated to mention this? It just describes creating a config struct and then immediately using it, but that alone isn't enough to get started.

**Comment by CMCDragonkai** [comment]
If we're only using QUIC as a raw data stream connection, what is a suitable ALPN? I'm looking at https://www.iana.org/assignments/tls-extensiontype-values/tls-extensiontype-values.xhtml#alpn-protocol-ids and there's no "generic data ALPN". Seems like the quiche library demands that an ALPN is set.

Can I make up our own default ALPN then?

**Comment by LPardue** [comment]
QUIC streams carry application data. If your using them then you have an application protocol and should define an ALPN. There's no way around this, the QUIC transport doesn't have opinion how you use streams, so there is no notion of generic data. 

You can define your own ALPN for your use case. And in doing that I encourage you to read the applicability document that explains many considerations to make when considering how to use QUIC - https://www.rfc-editor.org/rfc/rfc9308.html
