### ISSUE TITLE
h3::Connection::send_response only sends headers

### ISSUE THREAD

**Issue by keepsimple1** [cloudflare/quiche#530]
This fn name `send_response` is confusing as it only sends headers:
https://github.com/cloudflare/quiche/blob/98757caf1f36ac4236174d9ebae09ac027e78df6/src/h3/mod.rs#L636-L643

At the very least, the doc of `send_response` should clearly say it only sends headers.

And It seems clearer for users to call `send_headers` and then `send_body` (if needed). Is it possible to make `send_headers` public?

**Comment by LPardue** [comment]
The HTTP/3 specification is pretty clear on what comprises a request or response message, see https://tools.ietf.org/html/draft-ietf-quic-http-27#section-4.1.

An HTTP message by definition has to begin with headers, following elements (body or trailers) are optional message elements all depend on the the applicationation setting fin or not. The documentation describes how a server can respond to requests at https://github.com/cloudflare/quiche/blob/98757caf1f36ac4236174d9ebae09ac027e78df6/src/h3/mod.rs#L121

Exposing `send_headers()` is not something I'd want to do because it exposes a primitive that risks applications confusing the message ordering rules.

**Comment by keepsimple1** [comment]
Yes, my understanding is that by definition the HTTP response consists of headers _and_ optional body. 

The current `send_response` API in quiche does not send the whole response. It sends only the headers.  The user has to call `send_body` explicitly after calling `send_response`. 

IMO, either of the following options will be clearer: 

1. call `send_response` that can send headers and optional body, trailers.
or
2. call `send_headers` followed by `send_body` if needed. 

I have no problem with keeping `send_headers` private if `send_response` can be updated to actually send the whole response.

**Comment by LPardue** [comment]
The main benefit of the current design is it supports chunk-based streaming output.

In order to support your first option, the library would need to take and buffer all of the response body. However, there are scenarios where that is not possible such as running quiche in a reverse proxy that receives response data piece by piece. The current design is flexible in supporting different use cases, and has better performance by avoiding buffering.

send_response is analogous to send_headers, with the addition that internally we can do extra work needed to manage and validate aspects of the H3 connection.

**Comment by keepsimple1** [comment]
I think it's possible to have the `send_response` to send the whole response and support chunk-based streaming output. 

One way is to use something like `Response` in crate [http](https://docs.rs/http/0.2.1/http/response/struct.Response.html)  where `body` is generic and support streaming as long as `body` implements [`stream` trait](https://docs.rs/futures/0.3.5/futures/stream/trait.Stream.html).  `send_response` can poll the body stream without extra buffering.

**Comment by LPardue** [comment]
Making the API more advanced would make things more complicated for the C API. I'm not seeing what substantial benefit the proposals bring above what we have today. If you have suggestions for improving the method documentation, please file a PR.
