### ISSUE TITLE
how to use quiche as lib on Android platform

### ISSUE THREAD

**Issue by ZhihuiYang** [cloudflare/quiche#58]
I am trying to build quiche with Android NDK toolchain. but failed. it seems caused by ring. does anyone has done it successfully?

**Comment by ghedo** [comment]
@junhochoi and @lohith-bellad are going through building quiche for Android as well, and will be looking into this build failure.

**Comment by junhochoi** [comment]
@ZhihuiYang actually ring is not a issue once you have an android cross building environment. See https://mozilla.github.io/firefox-browser-architecture/experiments/2017-09-21-rust-on-android.html for how to set up cross build environment, but what is missing here is you need to add to $PATH for finding linker (compiler) file without a full path.

For example, when you build aarch64 platform, you need to add `<project path>/greetings/NDK/arm64/bin/` to your $PATH in above URL. When it will build with ring, but still quiche fails because Android related parameter is not setup when quiche try to build boringssl.

I open a PR (#70) for fixing quiche + boringssl build. Please try it out.

**Comment by ghedo** [comment]
@ZhihuiYang we now have instructions on how to build for Androind thanks to @junhochoi, see https://github.com/cloudflare/quiche#building-for-android

**Comment by ZhihuiYang** [comment]
@ghedo And @junhochoi thanks for your kindly help
