### ISSUE TITLE
How to use on_timeout() and timeout()

### ISSUE THREAD

**Issue by coolcih** [cloudflare/quiche#779]
I am studying QUICHE codes. I met packet loss with my codes. Is there sample codes with QUICHE for handling packet loss? It seems 2 related functions timeout() and on_timeout() in lib.rs. But I don't know how to use it.

**Comment by LPardue** [comment]
In case you missed it the relevant docs are

- https://docs.quic.tech/quiche/struct.Connection.html#method.timeout
- https://docs.quic.tech/quiche/struct.Connection.html#method.on_timeout

To explain a little, quiche has a number of internal timeout clocks one of which is for packet loss detection. `timeout()` returns the value of the timer expiration, which an application can use, in e.g. its event loop, to decide when to call `on_timeout()`. `on_timeout()` can provoke actions inside quiche to prepare recovery packets, but you need to make sure that `[send()](https://docs.quic.tech/quiche/struct.Connection.html#method.send)` is called in order to actually prepare the QUIC packet for the application to then send on a socket.

**Comment by coolcih** [comment]
@LPardue，Thanks for valuable answer! I know how to use it now. Summary as below:
1. Use function quiche_conn_timeout_as_nanos or quiche_conn_timeout_as_millis get the timeout value set in quiche.
2. Start a timer with the timeout value in step 1 after data send and implement a timeout function e.g. timeout_cb.
3. Once timeout, function quiche_conn_on_timeout must be called in timeout_cb to give  quiche chance process the packet loss.

Reference sample codes client.c(funcion: timeout_cb and flush_egress) in quiche.
