### ISSUE TITLE
quiche has too many small packets

### ISSUE THREAD

**Issue by lilongyan-huawei** [cloudflare/quiche#872]
Hi, there

I found many small packets during a request. 
so, would the total cost time of the request go down if we merge multiple small packets into one ?
￼￼￼￼

**Comment by lilongyan-huawei** [comment]
![image](https://user-images.githubusercontent.com/46128592/110590801-3c8dff00-81b3-11eb-9d34-1e9053dcad9b.png)
![image](https://user-images.githubusercontent.com/46128592/110590866-50d1fc00-81b3-11eb-939e-03a732b0c930.png)

**Comment by mickel8** [comment]
I think that it's not quiche specific. I suppose these packets are QPACK messages. If you compare HTTP/3 request with HTTP/2 one you will probably see similar behaviour.

**Comment by LPardue** [comment]
In that trace, you can see there are packets that contain STREAM frames for different IDs. This can help avoid HoL blocking if some of the packets get lost. Coalescing STREAM frames for different IDs into one packet means that HoL blocking chances increase. The actual effect of different packing strategies on e.g. HTTP performance is pretty hard to predict because it depends on the characteristics of the network that QUIC is running over. So I'd want to see compelling evidence that the current approach is problematic before rushing to any conclusion.
