### ISSUE TITLE
Is there a way to customize timeout for Http3 request?

### ISSUE THREAD

**Issue by keepsimple1** [cloudflare/quiche#908]
I'm using `h3::Connection::send_request` and `send_body` to send Http3 request. Is there a way to set a timeout for a particular h3 request? (I cannot find it in the config or h3 API). Thanks.

**Comment by LPardue** [comment]
quiche runs pretty close to the protocol level and while QUIC defines a connection-level timeout, it doesn't define one for streams. quiche allows endpoints to control the idle timeout period as part of the configuration.

quiche's H3 layer is quite thin and focused on the H3 protocol wire format, which also does not have a concept of a stream timeout. so there is no explicit request timeout in quiche.

Since QUIC or H3 protocols don't define request timeouts, such a feature in the quiche library would have to be custom. In addition, its not clear this would be a benefit to applications for the reasons in the next paragraph.

quiche helps people send or receive HTTP messages; there are many aspects of HTTP semantics that need to handled by applications using these messages. Timeouts are a good example, an app using the quiche library could to run its own timers measuring TTFB, time between headers and payload, time between DATA chunks, etc. and decide itself how to act. 

I'm not really sure there is anything quiche can do to help that wouldn't already be better handled in a higher level. But maybe you can explain more?

**Comment by keepsimple1** [comment]
Thanks. The raw requirement is really to "find out if the h3 server is not responding to this request", and for these requests we don't want to wait till the default connection idle timeout (20 seconds). I'll look into how to do it at the application level.

Regarding controlling the connection idle timeout, did you mean the API [set_max_idle_timeout()](https://docs.rs/quiche/0.8.1/quiche/struct.Config.html#method.set_max_idle_timeout) ? Its doc says "The default value is infinite", but somehow my experience is that the default timeout is 20 seconds, is it a different thing?

**Comment by LPardue** [comment]
The API controls the value sent by the instance of quiche in its Transport parameters. But the QUIC connection's effective idle timeout is computed based on the value sent by both - see https://tools.ietf.org/html/draft-ietf-quic-transport-34#section-10.1

It sound like the peer is sending you a value of 20 seconds.

**Comment by keepsimple1** [comment]
Thanks a lot for the answers!
